---
# tasks file for consulfirewallrole
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

# 5141 - Logstash rsyslog port on logs.*, required access from ALL hosts.
- name: Logstash rsyslog port on logs
  ansible.posix.firewalld:
    port: 5141/udp
    zone: internal
    permanent: yes
    state: enabled

# 9100 - Node exporter on ALL hosts, required access by metrics.*.
- name: Open node exporter on all hosts to the metrics IPs.
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 source address="{{ item }}"/32 port port=9100 protocol=tcp  accept
    zone: internal
    permanent: yes
    state: enabled
  loop: "{{ metrics_list }}"

# 9104 - MySQL exporter on app.* hosts, required access by metrics.*.
- name: Open MySQL exporter on app
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 source address="{{ item }}"/32 port port=9104 protocol=tcp  accept
    zone: internal
    permanent: yes
    state: enabled
  loop: "{{ metrics_list }}"
  when: "'app' in inventory_hostname"

# 3306 - MySQL database on app.*, requried access by backups.*.
- name: MySQL database on app
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 source address="{{ item }}"/32 port port=3306 protocol=tcp  accept
    zone: internal
    permanent: yes
    state: enabled
  loop: "{{ backups_list }}"
  when: "'app' in inventory_hostname"
